[alias]
rr = "run --release"

# https://github.com/rui314/mold?tab=readme-ov-file#how-to-use
# check binary for mold with:
#   $ readelf -p .comment target/release/<binary>
[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

